#!/usr/bin/env bash
# Non-Docker local install: clone ComfyUI next to this repo and wire folders.
# Use when Docker is unavailable. Still needs Python 3.12+ and (for video) NVIDIA CUDA PyTorch.
#
# Usage:
#   ./scripts/install-local.sh
#   COMFYUI_HOME=/path/to/ComfyUI ./scripts/install-local.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMFYUI_HOME="${COMFYUI_HOME:-${ROOT}/.local/ComfyUI}"
COMFYUI_REF="${COMFYUI_REF:-master}"

echo "=== Local ComfyUI install (Grok bridge) ==="
echo "Repo:         ${ROOT}"
echo "ComfyUI home: ${COMFYUI_HOME}"
echo

if [ ! -d "${COMFYUI_HOME}/.git" ]; then
  echo "[clone] ComfyUI → ${COMFYUI_HOME}"
  mkdir -p "$(dirname "${COMFYUI_HOME}")"
  git clone --depth 1 --branch "${COMFYUI_REF}" https://github.com/comfyanonymous/ComfyUI.git "${COMFYUI_HOME}"
else
  echo "[skip] ComfyUI already present"
fi

echo "[pip] ComfyUI requirements (current python: $(python3 --version 2>&1))"
python3 -m pip install --upgrade pip
python3 -m pip install -r "${COMFYUI_HOME}/requirements.txt"
python3 -m pip install opencv-python-headless imageio imageio-ffmpeg 2>/dev/null || true

# Wire shared folders via extra_model_paths + symlinks for I/O and workflows
EXTRA="${COMFYUI_HOME}/extra_model_paths.yaml"
cat > "${EXTRA}" <<EOF
# Generated by install-local.sh — Grok Build exclusive layout
grok_bridge:
  base_path: ${ROOT}/
  checkpoints: models/checkpoints/
  diffusion_models: models/diffusion_models/
  text_encoders: models/text_encoders/
  vae: models/vae/
  clip_vision: models/clip_vision/
  upscale_models: models/upscale_models/
  loras: models/loras/
  embeddings: models/embeddings/
  custom_nodes: custom_nodes/
EOF
echo "[ok] wrote ${EXTRA}"

# Symlink input/output/workflows into ComfyUI defaults when missing
link_dir() {
  local src="$1" dest="$2"
  mkdir -p "$(dirname "${dest}")"
  if [ -L "${dest}" ] || [ -e "${dest}" ]; then
    echo "[skip] ${dest}"
    return 0
  fi
  ln -s "${src}" "${dest}"
  echo "[link] ${dest} → ${src}"
}

link_dir "${ROOT}/input" "${COMFYUI_HOME}/input"
link_dir "${ROOT}/output" "${COMFYUI_HOME}/output"
mkdir -p "${COMFYUI_HOME}/user/default/workflows"
# Copy workflows (symlink whole dir can fight ComfyUI user dir creation)
cp -n "${ROOT}/workflows/"*.json "${COMFYUI_HOME}/user/default/workflows/" 2>/dev/null || \
  cp "${ROOT}/workflows/"*.json "${COMFYUI_HOME}/user/default/workflows/"
echo "[ok] workflows copied to ComfyUI user folder"

export COMFYUI_CUSTOM_NODES="${ROOT}/custom_nodes"
echo "[nodes] installing recommended custom nodes into ${COMFYUI_CUSTOM_NODES}"
bash "${ROOT}/scripts/install-custom-nodes.sh" || true

# Also seed Manager into ComfyUI's own custom_nodes if empty of Manager
if [ ! -d "${COMFYUI_HOME}/custom_nodes/ComfyUI-Manager" ]; then
  if [ -d "${ROOT}/custom_nodes/ComfyUI-Manager" ]; then
    ln -s "${ROOT}/custom_nodes/ComfyUI-Manager" "${COMFYUI_HOME}/custom_nodes/ComfyUI-Manager" || true
  fi
fi

cat > "${ROOT}/scripts/run-local.sh" <<EOF
#!/usr/bin/env bash
# Generated by install-local.sh
set -euo pipefail
cd "${COMFYUI_HOME}"
exec python3 main.py --listen 0.0.0.0 --port 8188 --enable-cors-header --preview-method auto "\$@"
EOF
chmod +x "${ROOT}/scripts/run-local.sh"

echo
echo "=== Local install ready ==="
echo "1. Models:  ./scripts/download-models.sh minimal"
echo "2. Start:   ./scripts/run-local.sh"
echo "3. Open:    http://localhost:8188"
echo
echo "Note: install a CUDA build of PyTorch matching your GPU for Wan I2V."
echo "      See https://pytorch.org/get-started/locally/"
